version: "3.7"
services:
  database:
    image: postgres
    restart: always
    networks:
      - backend
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  server:
    build:
      context: .
      # dockerfile: timetable_server/Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - backend
    ports:
    - "3000:3000"
volumes:
  data:

networks:
  backend:
    driver: bridge
    name: backend