name: Build dev

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    name: Build and upload artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.13.1'

      # - name: Run tests
      #   run: go test

      - name: Generate docs
        run: |
         chmod +x ./docgen.sh
         ./docgen.sh
        shell: bash

      - name: Build
        run: go build -o ./dist/server ./cmd/main.go 

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: Build ${{ github.run_number }}
          path: ./dist/server

      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: Docs ${{ github.run_number }}
          path: .\docs
  docs:
    name: Upload docs
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get docs
        uses: actions/download-artifact@v3
        with:
          name: Docs ${{ github.run_number }}
          
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .